# Generated by Django 3.2 on 2021-04-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ccsformdata_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccsformdata',
            name='Child_ECE_StartDate_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='Child_ECE_StartDate_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='Child_ECE_StartDate_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='Child_ECE_StartDate_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='childDOB_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='childDOB_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='childDOB_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='childDOB_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='childDOB_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='courseEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='courseStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='dateArrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='dateGranted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='p_courseEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='p_courseStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='p_dateArrived',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='p_dateGranted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='p_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccsformdata',
            name='partnerDOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
